version: '3.9'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env  
    expose:
      - "9000"
    restart: unless-stopped
 